export const dataTickets = [
  {
    id: 1,
    title_ticket: "Tickets 1",
    received_date: new Date().toISOString(),
    ticket_id: 1996,
    priority: 1,
    urgency: 1,
    category: 1,
    status: 1,
    members: [1, 2],
    client_name: "Client singapore",
    assigneeByMe: true
  },
  {
    id: 2,
    title_ticket: "Tickets 2",
    received_date: new Date().toISOString(),
    ticket_id: 1992,
    priority: 5,
    urgency: 2,
    category: 4,
    status: 2,
    members: [3, 4],
    client_name: "Client India",
  },
  {
    id: 3,
    title_ticket: "Tickets 3",
    received_date: new Date().toISOString(),
    ticket_id: 1993,
    priority: 4,
    urgency: 3,
    category: 1,
    status: 3,
    members: [4, 5, 6],
    client_name: "Client Korea",
    assigneeByMe: true
  },
  {
    id: 4,
    title_ticket: "Tickets 4",
    received_date: new Date().toISOString(),
    ticket_id: 1991,
    priority: 2,
    urgency: 4,
    category: 2,
    status: 2,
    members: [6, 1],
    client_name: "Client Japan",
  },
  {
    id: 5,
    title_ticket: "Tickets 5",
    received_date: new Date().toISOString(),
    ticket_id: 1994,
    priority: 3,
    urgency: 5,
    category: 3,
    status: 1,
    members: [3, 6],
    client_name: "Client US",
    assigneeByMe: true
  },
  {
    id: 6,
    title_ticket: "Tickets 6",
    received_date: new Date().toISOString(),
    ticket_id: 1996,
    priority: 1,
    urgency: 1,
    category: 1,
    status: 1,
    members: [1, 3],
    client_name: "Client singapore",
    assigneeByMe: true
  },
  {
    id: 7,
    title_ticket: "Tickets 7",
    received_date: new Date().toISOString(),
    ticket_id: 1992,
    priority: 5,
    urgency: 2,
    category: 4,
    status: 2,
    members: [5, 3],
    client_name: "Client India",
  },
  {
    id: 8,
    title_ticket: "Tickets 8",
    received_date: new Date().toISOString(),
    ticket_id: 1993,
    priority: 4,
    urgency: 3,
    category: 1,
    status: 3,
    members: [1, 3, 5],
    client_name: "Client Korea",
    assigneeByMe: true
  },
  {
    id: 9,
    title_ticket: "Tickets 9",
    received_date: new Date().toISOString(),
    ticket_id: 1991,
    priority: 2,
    urgency: 4,
    category: 2,
    status: 2,
    members: [2, 3],
    client_name: "Client Japan",
  },

  {
    id: 10,
    title_ticket: "Tickets 10",
    received_date: new Date().toISOString(),
    ticket_id: 1994,
    priority: 3,
    urgency: 5,
    category: 3,
    status: 1,
    members: [1, 2],
    client_name: "Client US",
    assigneeByMe: true
  },
  {
    id: 11,
    title_ticket: "Tickets 11",
    received_date: new Date().toISOString(),
    ticket_id: 1996,
    priority: 1,
    urgency: 1,
    category: 1,
    status: 1,
    members: [3, 4],
    client_name: "Client singapore",
    assigneeByMe: true
  },
  {
    id: 12,
    title_ticket: "Tickets 12",
    received_date: new Date().toISOString(),
    ticket_id: 1992,
    priority: 5, urgency: 2,
    category: 4, status: 2,
    members: [5, 6],
    client_name: "Client India",
  },
  {
    id: 13,
    title_ticket: "Tickets 13",
    received_date: new Date().toISOString(),
    ticket_id: 1993,
    priority: 4,
    urgency: 3,
    category: 1,
    status: 3,
    members: [1, 4, 2],
    client_name: "Client Korea",
    assigneeByMe: true
  },
  {
    id: 14,
    title_ticket: "Tickets 14",
    received_date: new Date().toISOString(),
    ticket_id: 1991,
    priority: 2,
    urgency: 4,
    category: 2,
    status: 2,
    members: [1],
    client_name: "Client Japan",
  },
  {
    id: 15,
    title_ticket: "Tickets 15",
    received_date: new Date().toISOString(),
    ticket_id: 1994,
    priority: 3,
    urgency: 5,
    category: 3,
    status: 1,
    members: [2],
    client_name: "Client US",
    assigneeByMe: true
  },
  {
    id: 16,
    title_ticket: "Tickets 16",
    received_date: new Date().toISOString(),
    ticket_id: 1996,
    priority: 1,
    urgency: 1,
    category: 1,
    status: 1,
    members: [3],
    client_name: "Client singapore",
    assigneeByMe: true
  },
  {
    id: 17,
    title_ticket: "Tickets 17",
    received_date: new Date().toISOString(),
    ticket_id: 1992,
    priority: 5,
    urgency: 2,
    category: 4,
    status: 2,
    members: [4],
    client_name: "Client India",
  },
  {
    id: 18,
    title_ticket: "Tickets 18",
    received_date: new Date().toISOString(),
    ticket_id: 1993,
    priority: 4,
    urgency: 3,
    category: 1,
    status: 3,
    members: [5],
    client_name: "Client Korea",
    assigneeByMe: true
  },
  {
    id: 19,
    title_ticket: "Tickets 19",
    received_date: new Date().toISOString(),
    ticket_id: 1991,
    priority: 2,
    urgency: 4,
    category: 2,
    status: 2,
    members: [6],
    client_name: "Client Japan",
  },
  {
    id: 20,
    title_ticket: "Tickets 20",
    received_date: new Date().toISOString(),
    ticket_id: 1994,
    priority: 3,
    urgency: 5,
    category: 3,
    status: 1,
    members: [3, 1],
    client_name: "Client US",
    assigneeByMe: true
  },
  {
    id: 21,
    title_ticket: "Tickets 21",
    received_date: new Date().toISOString(),
    ticket_id: 1996,
    priority: 1,
    urgency: 1,
    category: 1,
    status: 1,
    members: [2, 3],
    client_name: "Client singapore",
    assigneeByMe: true
  },
  {
    id: 22,
    title_ticket: "Tickets 22",
    received_date: new Date().toISOString(),
    ticket_id: 1992,
    priority: 5,
    urgency: 2,
    category: 4,
    status: 2,
    members: [1, 4],
    client_name: "Client India",
  },
  {
    id: 23,
    title_ticket: "Tickets 23",
    received_date: new Date().toISOString(),
    ticket_id: 1993,
    priority: 4,
    urgency: 3,
    category: 1,
    status: 3,
    members: [1, 3, 2],
    client_name: "Client Korea",
    assigneeByMe: true
  },
  {
    id: 24,
    title_ticket: "Tickets 24",
    received_date: new Date().toISOString(),
    ticket_id: 1991,
    priority: 2,
    urgency: 4,
    category: 2,
    status: 2,
    members: [3],
    client_name: "Client Japan",
  },
  {
    id: 25,
    title_ticket: "Tickets 25",
    received_date: new Date().toISOString(),
    ticket_id: 1994,
    priority: 3,
    urgency: 5,
    category: 3,
    status: 1,
    members: [4, 5],
    client_name: "Client US",
    assigneeByMe: true
  }
]
